project_id = "qnpbfynreellcxvoxqph"

[functions.process-knowledge]
verify_jwt = true

[functions.chat-rag]
verify_jwt = true

[functions.generate-brainstorming]
verify_jwt = true

[functions.create-paypal-subscription]
verify_jwt = true

[functions.check-paypal-subscription]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false